import { G2G_TERMS_AND_CONDITIONS } from "./g2gTerms"

function moneyValue(value: any) {
  if (value === null || value === undefined || value === "") return "—"
  const n = Number(value)
  if (Number.isNaN(n)) return String(value)
  return `$${n.toLocaleString()}`
}

function escapeHtml(value: any) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

export function buildDocumentSnapshotHtml(doc: any, payload: any, statusLabel: string) {
  const rows = [
    ["Document", doc.document_title],
    ["Package Type", doc.package_type],
    ["Customer", payload.customer_name],
    ["Phone", payload.customer_phone],
    ["Email", payload.customer_email],
    ["Address", payload.job_address],
    ["Proposal Amount", moneyValue(payload.proposal_amount ?? payload.agreed_amount)],
    ["Contract Amount", moneyValue(payload.contract_amount ?? payload.proposal_amount ?? payload.agreed_amount)],
    ["Discount Amount", moneyValue(payload.discount_amount)],
    ["Discount Reason", payload.discount_reason],
    ["Roof Type", payload.roof_type],
    ["Roof Squares", payload.roof_squares],
    ["Carrier Approved Amount", moneyValue(payload.carrier_approved_amount)],
    ["Claim Number", payload.claim_number],
    ["Deductible", payload.deductible],
    ["Estimator Remarks", payload.estimator_remarks],
    ["Terms Accepted", payload.terms_accepted === true ? "Yes" : "No / Not signed yet"],
    ["Signed By", payload.signed_by],
    ["Signed At", payload.signed_at],
  ]

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(doc.document_title)} - ${escapeHtml(statusLabel)}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #111; padding: 32px; line-height: 1.45; }
    h1 { margin-bottom: 4px; }
    .muted { color: #555; margin-bottom: 24px; }
    table { border-collapse: collapse; width: 100%; margin-top: 18px; margin-bottom: 28px; }
    td { border: 1px solid #ddd; padding: 10px; vertical-align: top; }
    td:first-child { font-weight: bold; width: 260px; background: #f7f7f7; }
    section { margin-top: 28px; }
    .terms { white-space: pre-wrap; border: 1px solid #ddd; padding: 18px; background: #fafafa; }
    .signature { margin-top: 32px; padding-top: 16px; border-top: 2px solid #111; }
  </style>
</head>
<body>
  <h1>Good2Go Roofing ${escapeHtml(statusLabel)}</h1>
  <div class="muted">Generated by Contractor Navigator</div>
  <table>
    ${rows.map(([label, value]) => `<tr><td>${escapeHtml(label)}</td><td>${escapeHtml(value || "—")}</td></tr>`).join("\n")}
  </table>

  <div class="signature">
    <strong>Electronic Signature:</strong> ${escapeHtml(payload.signed_by || "Not signed yet")}<br />
    <strong>Signed At:</strong> ${escapeHtml(payload.signed_at || "—")}<br />
    <strong>Terms Accepted:</strong> ${payload.terms_accepted === true ? "Yes" : "No / Not signed yet"}<br />
    <strong>Electronic Signature Statement:</strong> Typed signature accepted as electronic signature.
  </div>

  <section>
    <h2>Terms and Conditions</h2>
    <div class="terms">${escapeHtml(G2G_TERMS_AND_CONDITIONS)}</div>
  </section>
</body>
</html>`
}
